name: Daily RAM Price Scraper

on:
  schedule:
    - cron: '0 14 * * *'  # 08:00 Guatemala (UTC-6)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          R_Shop1: ${{ secrets.R_Shop1 }}
          R_Shop2: ${{ secrets.R_Shop2 }}
          R_Shop3: ${{ secrets.R_Shop3 }}
          R_Shop4: ${{ secrets.R_Shop4 }}
          R_Shop5: ${{ secrets.R_Shop5 }}
          R_Shop6: ${{ secrets.R_Shop6 }}
          R_Shop7: ${{ secrets.R_Shop7 }}
          R_Shop8: ${{ secrets.R_Shop8 }}
          R_Shop9_1: ${{ secrets.R_Shop9_1 }}
          R_Shop9_2: ${{ secrets.R_Shop9_2 }}
          S_Shop1: ${{ secrets.S_SHOP1 }}
          S_Shop2_1: ${{ secrets.S_SHOP2_1 }}
          S_Shop2_2: ${{ secrets.S_SHOP2_2 }}
          S_Shop2_3: ${{ secrets.S_SHOP2_3 }}
          S_Shop3: ${{ secrets.S_Shop3 }}
          S_Shop4: ${{ secrets.S_Shop4 }}
          S_Shop5_1: ${{ secrets.S_Shop5_1 }}
          S_Shop5_2: ${{ secrets.S_SHOP5_1 }}
          Conf_Shop1: ${{ secrets.Conf_Shop1 }}
          Conf_Shop2: ${{ secrets.Conf_Shop2 }}
          Conf_Shop3: ${{ secrets.CONF_SHOP3 }}
          Conf_Shop4: ${{ secrets.CONF_SHOP4 }}
          Conf_Shop5: ${{ secrets.CONF_SHOP5 }}
          sb_url: ${{ secrets.sb_url }}
          sb_secret: ${{ secrets.sb_secret }}

        run: |
          python src/main.py
